// 20231215145615
// http://universities.hipolabs.com/search?country=Kazakhstan

const learnJSON = [
  {
    name: "Abylai Khan University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.ablaikhan.kz/"],
    domains: ["ablaikhan.kz"],
  },
  {
    name: "Kazak State University of Agriculture",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.agriun.almaty.kz/"],
    domains: ["agriun.almaty.kz"],
  },
  {
    name: "Aktau State University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.aktsu.kz/"],
    domains: ["aktsu.kz"],
  },
  {
    name: "Atyrau State University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.atgu.kz/"],
    domains: ["atgu.kz"],
  },
  {
    name: "East Kazakstan State Technical University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.ektu.kz/"],
    domains: ["ektu.kz"],
  },
  {
    name: "L.N. Gumilyov Eurasian National University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.enu.kz/"],
    domains: ["enu.kz"],
  },
  {
    name: "Eurasian Institute of market",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.eurazir.kz/"],
    domains: ["eurazir.kz"],
  },
  {
    name: "Kazak American University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.kau.kz/"],
    domains: ["kau.kz"],
  },
  {
    name: "Turar Ryskulov Kazakh Economic University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.kazeu.kz/"],
    domains: ["kazeu.kz"],
  },
  {
    name: "Abai State University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.kaznpu.kz/"],
    domains: ["kaznpu.kz"],
  },
  {
    name: "Kazak National Technical University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.kazntu.kz/"],
    domains: ["kazntu.kz"],
  },
  {
    name: "Al-Farabi Kazakh National University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.kaznu.kz/"],
    domains: ["kaznu.kz"],
  },
  {
    name: "Kazakh British Technical University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.kbtu.kz/"],
    domains: ["kbtu.kz"],
  },
  {
    name: "Kazakhstan Institute of Management, Economics, and Strategic Research",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.kimep.kz/"],
    domains: ["kimep.kz"],
  },
  {
    name: "Karaganda State Technical University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.kstu.kz/"],
    domains: ["kstu.kz"],
  },
  {
    name: "Kostanai State University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.ksu.kst.kz/"],
    domains: ["ksu.kst.kz"],
  },
  {
    name: "Karaganda State Buketov University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.ksu.kz/"],
    domains: ["ksu.kz"],
  },
  {
    name: "North Kazakhstan State University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.nkzu.kz/"],
    domains: ["nkzu.kz"],
  },
  {
    name: "Pavlodar University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.psu.kz/"],
    domains: ["psu.kz"],
  },
  {
    name: "Suleyman Demirel University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.sdu.edu.kz/"],
    domains: ["sdu.edu.kz"],
  },
  {
    name: "Semey State University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.semgu.kz/"],
    domains: ["semgu.kz"],
  },
  {
    name: "Semey State Medical University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.sgma.kz/"],
    domains: ["sgma.kz"],
  },
  {
    name: "International Kazakh-Turkish University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.turkistan.kz/"],
    domains: ["turkistan.kz"],
  },
  {
    name: "University of International Business",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.uib.kz/"],
    domains: ["uib.kz"],
  },
  {
    name: "East Kazakhstan State University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.vkgu.kz/"],
    domains: ["vkgu.kz"],
  },
  {
    name: "Western Kazakhstan Agricultural University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.wkau.kz/"],
    domains: ["wkau.kz"],
  },
  {
    name: "Zhezkazgan Baikonurov University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.zhezu.kz/"],
    domains: ["zhezu.kz"],
  },
  {
    name: "Zhetysu State University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["http://www.zhgu.kz/"],
    domains: ["zhgu.kz"],
  },
  {
    name: "Nazarbayev University",
    country: "Kazakhstan",
    "state-province": null,
    alpha_two_code: "KZ",
    web_pages: ["https://nu.edu.kz/"],
    domains: ["nu.edu.kz"],
  },
];

const myData = [
  {
    picture:
      "https://w.forfun.com/fetch/c4/c4278a31d1820f1df09421a893726338.jpeg",
    header: "Lorem, ipsum dolor.",
    paragraph:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Id, iure!",
  },
  {
    picture:
      "https://gorodprizrak.com/wp-content/uploads/2023/06/d32f33b6b9bb5375f6d02747d0475f5f.jpg",
    header: "Lorem, ipsum dolor.",
    paragraph:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Id, iure!",
  },
  {
    picture:
      "https://haski-mana.ru/wp-content/uploads/9/7/f/97ff17a75a0da216609492daad6d248d.jpeg",
    header: "Lorem, ipsum dolor.",
    paragraph:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Id, iure!",
  },
];
